spring.application.name=open-share-application
spring.main.allow-bean-definition-overriding=true


supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.rest=${SUPABASE_REST}
logging.level.org.springframework.core.env=DEBUG
server.port=${PORT:8080}

spring.jackson.property-naming-strategy=SNAKE_CASE